server:
  port: 9006

spring:
  application:
    name: ADDRESS-SERVICE
  flyway:
    baselineOnMigrate: true
    locations: classpath:/db/migration
    validateOnMigrate: false
    enabled: true
  datasource:
    initialization-mode: always
    platform: postgres
    url: jdbc:postgresql://localhost:5432/zemosodiagnostics
    username: bc41
    password: test123
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

logging:
  level:
    org:
      springframework: ERROR


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost

