server:
  port: 9007

spring:
  application:
    name: APPOINTMENT-SERVICE
  flyway:
    baselineOnMigrate: true
    validateOnMigrate: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost
