image: maven:latest
variables:
  SONAR_TOKEN: $SONAR_TOKEN_APPOINTMENTSERVICE
  SONAR_HOST_URL: "https://sonarcloud.io"
  GIT_DEPTH: 0

sonarcloud-backend-user:
  stage: sonar
  script:
    - cd "${CI_PROJECT_DIR}/backend/cardservice"
    - mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=com.zemoso.appointment -Dsonar.login=$SONAR_TOKEN_APPOINTMENTSERVICE -Dsonar.organization=zemoso-int
      -Dsonar.qualitygate.wait=true
  allow_failure: true
  only:
    - merge_requests
    - dev
    - main