server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: PATIENT-SERVICE
          uri: lb://PATIENT-SERVICE
          predicates:
            - Path=/patients/**
        - id: TEST-SERVICE
          uri: lb://TEST-SERVICE
          predicates:
            - Path=/tests/**
        - id: LAB-SERVICE
          uri: lb://LAB-SERVICE
          predicates:
            - Path=/labs/**
        - id: ADDRESS-SERVICE
          uri: lb://ADDRESS-SERVICE
          predicates:
            - Path=/address/**
        - id: CARD-SERVICE
          uri: lb://CARD-SERVICE
          predicates:
            - Path=/cards/**
        - id: APPOINTMENT-SERVICE
          uri: lb://APPOINTMENT-SERVICE
          predicates:
            - Path=/appointments/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost